# Generated by Django 2.2.19 on 2022-10-21 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20221021_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': (), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': (), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
